### ISSUE TITLE
Does not build (MSBuild 12.0)

### ISSUE THREAD

**Issue by SegaRetro** [LuigiBlood/hcgcad#5]
Every commit after 1c0623040da254ca9266fe516101de9b7123e4cc does not build with MSBuild 12.0, it gives 3 errors when building that all mention this line:

``
 gif.Add(0b00001001);
``

These are the errors when building commit 3d635bf563f5b01ae3d916cac6f49d05f38ef990:

``
Program.cs(175,26): error CS1026: ) expected [D:\User Files\Downloads\hcgcad-main\hcgcad-main\hcgcad\hcgcad.csproj]
Program.cs(175,35): error CS1002: ; expected [D:\User Files\Downloads\hcgcad-main\hcgcad-main\hcgcad\hcgcad.csproj]
Program.cs(175,35): error CS1525: Invalid expression term ')' [D:\User Files\Downloads\hcgcad-main\hcgcad-main\hcgcad\hcgcad.csproj]
``

**Comment by LuigiBlood** [comment]
I can switch it to hex I guess

**Comment by LuigiBlood** [comment]
Fixed with https://github.com/LuigiBlood/hcgcad/commit/0fbd08000aacd6c89deda037ccd69c3264ce7324
